import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: 'C:/Users/seitaro.taketani/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:8080/#y=2024&p=filtration&d=AHS&r=Europe');
await page.waitForFunction(() => window.__wwtReady === true);
await page.waitForTimeout(1500);
const fps = () => page.evaluate(() => new Promise(res => { let n = 0; const t = performance.now(); const f = () => { n++; if (performance.now() - t < 1000) requestAnimationFrame(f); else res(n); }; requestAnimationFrame(f); }));
console.log('fps before', await fps());
let t0 = Date.now();
await page.selectOption('#year-select', '2012');
await page.waitForFunction(() => location.hash.includes('y=2012'), null, { timeout: 10000 });
console.log('year switch', Date.now() - t0, 'ms');
console.log('fps after', await fps());
t0 = Date.now();
await page.evaluate(() => { window.__t = performance.now(); });
await page.selectOption('#year-select', '2013');
await page.waitForFunction(() => location.hash.includes('y=2013'), null, { timeout: 10000 });
console.log('year switch 2', Date.now() - t0, 'ms');
await browser.close();
